services:
  flux-q4:
    build:
      context: .
    image: flux-q4-service:latest
    container_name: flux-q4-service
    # network_mode: host
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - ./.triton_cache:/root/.triton/cache
      - ./.pip_cache:/root/.cache/pip  
      - python_global_packages:/usr/local/lib/python3.12/site-packages/
    environment:
      # Offline Configurations
      - HF_HUB_OFFLINE=1
      - TRANSFORMERS_OFFLINE=1
      
      # Triton Cache & JIT Compilation Accelerators
      - TRITON_CACHE_DIR=/root/.triton/cache
      - TRITON_COMPILE_NUM_THREADS=8
      
      # Memory Allocator Tweaks (Prevents First-Run Autotuner OOMs)
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True,max_split_size_mb:128
  
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 'all'
              capabilities: [gpu]
    # restart: unless-stopped
    command: 'bash run.sh'

volumes:
  python_global_packages: 